# Toggle: chat_template_kwargs.enable_thinking = true|false
name = "Agents-A1"
description = "InferX agentic execution model"
attachment = true
reasoning = true
tool_call = true
structured_output = true
temperature = true
release_date = "2026-03-01"
last_updated = "2026-03-01"
open_weights = false

reasoning_options = [
  { type = "toggle" }
]

[modalities]
input = ["text", "image"]
output = ["text"]

[cost]
input = 0.00
output = 0.00

[limit]
context = 262_144
output = 100_000
